### ISSUE TITLE
Update this config to work with ESLint 4

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/eslint-config-sparkbox#7]
Here's a link to the release changes: https://github.com/eslint/eslint/releases/tag/v4.0.0

**Comment by pfulton** [comment]
One of our core dependencies, `eslint-config-airbnb`, is not yet up-to-date with ESLint `4.0.0` either: https://github.com/airbnb/javascript/issues/1447. Since we extend from their rules, I think we'll need to wait until that issue is closed before we proceed. There are several PRs in for that issue, though.

**Comment by pfulton** [comment]
Looks like we might be able to update this now: https://github.com/airbnb/javascript/issues/1447

**Comment by bryanbraun** [comment]
Closing this because sparkbox/eslint-config-sparkbox#8 was merged. 👍
